version: '3.6'
services:
  postgres:
    container_name: blogger
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  mongodb:
    image: mongo:latest
    container_name: mongodb_chat
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  postgres_data:
  mongodb_data: